version: '2'
services:
    smsvalidator-app:
        image: smsvalidator
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://smsvalidator-postgresql:5432/smsValidator
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    smsvalidator-postgresql:
        extends:
            file: postgresql.yml
            service: smsvalidator-postgresql
